spring:
  application:
    name: Shorten_URL
  datasource:
    url: jdbc:mysql://localhost:3306/short_URL?createDatabaseIfNotExist=true
    password:
    username: root
  jpa:
    show-sql: true

url-shortener:
  default-expiration-minutes: 5
  base-url: http://localhost:8080
  short-url-length: 8
  cleanup-interval-ms: 60000